### PR TITLE
16.6.0

### PR DESCRIPTION
**Pull request by williamjamir**

### CODE REVIEW

**Comment by jamesmyatt** [comment]
Any clues why the linux/python2.7 build is failing?
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=39450

**Comment by ocefpaf** [comment]
Copying the error here for visibility:

```
++ which python
+ virtualenv -p /home/conda/feedstock_root/build_artifacts/virtualenv_1559521733540/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python /tmp/venv-219
Already using interpreter $PREFIX/bin/python
New python executable in /tmp/venv-219/bin/python
/tmp/venv-219/bin/python: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
ERROR: The executable /tmp/venv-219/bin/python is not functioning
ERROR: It thinks sys.prefix is '$SRC_DIR' (should be u'/tmp/venv-219')
ERROR: virtualenv is not compatible with this system or executable
```

**Comment by jamesmyatt** [comment]
Is that saying that virtualenv 16.6.0 doesn't support Python 2.7 on Linux?

**Comment by ocefpaf** [comment]
I don't think the problem with python 2.7 is related to this PR. I guess it may be how we are finding the python from the docker image or build system there. I'm skipping that in #16 so we can finally fix this feedstock Thanks @williamjamir for refreshing the patches! I'm using them in #16.

**Pull request closed without merging**
